// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package pg_store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPermohonanAdmin = `-- name: CountPermohonanAdmin :one
SELECT COUNT(*) 
FROM permohonan p
JOIN penduduk pd ON p.nik = pd.nik
LEFT JOIN jadwal_sesi js ON p.jadwal_sesi_id = js.id
WHERE 
    ($1::text IS NULL OR 
     p.nik ILIKE '%' || $1 || '%' OR 
     p.kode_booking ILIKE '%' || $1 || '%' OR 
     pd.nama_lengkap ILIKE '%' || $1 || '%')
    AND ($2::text IS NULL OR p.status_terkini = $2)
    AND (
        ($3::smallint IS NOT NULL AND js.lokasi_kelurahan_id = $3)
        OR
        ($3::smallint IS NULL AND js.lokasi_kelurahan_id IS NULL)
    )
`

type CountPermohonanAdminParams struct {
	Search      pgtype.Text `json:"search"`
	Status      pgtype.Text `json:"status"`
	KelurahanID pgtype.Int2 `json:"kelurahanId"`
}

func (q *Queries) CountPermohonanAdmin(ctx context.Context, arg CountPermohonanAdminParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPermohonanAdmin, arg.Search, arg.Status, arg.KelurahanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAdminDashboardStats = `-- name: GetAdminDashboardStats :one
SELECT 
    COUNT(*) AS total_permohonan,
    COUNT(*) FILTER (WHERE status_terkini = 'VERIFIKASI') AS verifikasi,
    COUNT(*) FILTER (WHERE status_terkini = 'PROSES') AS proses,
    COUNT(*) FILTER (WHERE status_terkini = 'SIAP_AMBIL') AS siap_ambil,
    COUNT(*) FILTER (WHERE status_terkini = 'SELESAI') AS selesai,
    COUNT(*) FILTER (WHERE status_terkini = 'DITOLAK') AS ditolak
FROM permohonan p
LEFT JOIN jadwal_sesi js ON p.jadwal_sesi_id = js.id
WHERE (
    -- Admin Kelurahan: filter by their kelurahan
    ($1::smallint IS NOT NULL AND js.lokasi_kelurahan_id = $1)
    OR
    -- Admin Kecamatan: only see kecamatan-level data (NULL lokasi_kelurahan_id)
    ($1::smallint IS NULL AND js.lokasi_kelurahan_id IS NULL)
)
`

type GetAdminDashboardStatsRow struct {
	TotalPermohonan int64 `json:"totalPermohonan"`
	Verifikasi      int64 `json:"verifikasi"`
	Proses          int64 `json:"proses"`
	SiapAmbil       int64 `json:"siapAmbil"`
	Selesai         int64 `json:"selesai"`
	Ditolak         int64 `json:"ditolak"`
}

func (q *Queries) GetAdminDashboardStats(ctx context.Context, kelurahanID pgtype.Int2) (GetAdminDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminDashboardStats, kelurahanID)
	var i GetAdminDashboardStatsRow
	err := row.Scan(
		&i.TotalPermohonan,
		&i.Verifikasi,
		&i.Proses,
		&i.SiapAmbil,
		&i.Selesai,
		&i.Ditolak,
	)
	return i, err
}

const getDokumenByPermohonan = `-- name: GetDokumenByPermohonan :many
SELECT 
    id,
    file_path,
    jenis_dokumen,
    uploaded_at
FROM dokumen_syarat
WHERE permohonan_id = $1
`

type GetDokumenByPermohonanRow struct {
	ID           uuid.UUID        `json:"id"`
	FilePath     string           `json:"filePath"`
	JenisDokumen string           `json:"jenisDokumen"`
	UploadedAt   pgtype.Timestamp `json:"uploadedAt"`
}

func (q *Queries) GetDokumenByPermohonan(ctx context.Context, permohonanID pgtype.UUID) ([]GetDokumenByPermohonanRow, error) {
	rows, err := q.db.Query(ctx, getDokumenByPermohonan, permohonanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDokumenByPermohonanRow
	for rows.Next() {
		var i GetDokumenByPermohonanRow
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.JenisDokumen,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendudukStatsAdmin = `-- name: GetPendudukStatsAdmin :one
SELECT 
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE jenis_kelamin = 'LAKI_LAKI') AS laki_laki,
    COUNT(*) FILTER (WHERE jenis_kelamin = 'PEREMPUAN') AS perempuan,
    COUNT(*) AS wajib_ktp
FROM penduduk p
WHERE ($1::smallint IS NULL OR p.kelurahan_id = $1)
`

type GetPendudukStatsAdminRow struct {
	Total     int64 `json:"total"`
	LakiLaki  int64 `json:"lakiLaki"`
	Perempuan int64 `json:"perempuan"`
	WajibKtp  int64 `json:"wajibKtp"`
}

func (q *Queries) GetPendudukStatsAdmin(ctx context.Context, kelurahanID pgtype.Int2) (GetPendudukStatsAdminRow, error) {
	row := q.db.QueryRow(ctx, getPendudukStatsAdmin, kelurahanID)
	var i GetPendudukStatsAdminRow
	err := row.Scan(
		&i.Total,
		&i.LakiLaki,
		&i.Perempuan,
		&i.WajibKtp,
	)
	return i, err
}

const getPermohonanDetailAdmin = `-- name: GetPermohonanDetailAdmin :one
SELECT 
    p.id,
    p.kode_booking,
    p.nik,
    pd.nama_lengkap,
    pd.jenis_kelamin,
    pd.alamat,
    pd.no_hp as no_telp,
    k_penduduk.nama_kelurahan as kelurahan,
    p.jenis_permohonan,
    p.status_terkini,
    p.created_at as tanggal_daftar,
    js.tanggal as jadwal_tanggal,
    js.jam_mulai as jadwal_jam_mulai,
    js.jam_selesai as jadwal_jam_selesai,
    p.nomor_antrian_sesi as nomor_antrian,
    k_lokasi.nama_kelurahan as lokasi_permohonan
FROM permohonan p
JOIN penduduk pd ON p.nik = pd.nik
LEFT JOIN ref_kelurahan k_penduduk ON pd.kelurahan_id = k_penduduk.id
LEFT JOIN jadwal_sesi js ON p.jadwal_sesi_id = js.id
LEFT JOIN ref_kelurahan k_lokasi ON js.lokasi_kelurahan_id = k_lokasi.id
WHERE p.id = $1
  AND (
    ($2::smallint IS NOT NULL AND js.lokasi_kelurahan_id = $2)
    OR
    ($2::smallint IS NULL AND js.lokasi_kelurahan_id IS NULL)
  )
`

type GetPermohonanDetailAdminParams struct {
	ID          uuid.UUID   `json:"id"`
	KelurahanID pgtype.Int2 `json:"kelurahanId"`
}

type GetPermohonanDetailAdminRow struct {
	ID               uuid.UUID        `json:"id"`
	KodeBooking      pgtype.Text      `json:"kodeBooking"`
	Nik              pgtype.Text      `json:"nik"`
	NamaLengkap      string           `json:"namaLengkap"`
	JenisKelamin     string           `json:"jenisKelamin"`
	Alamat           pgtype.Text      `json:"alamat"`
	NoTelp           pgtype.Text      `json:"noTelp"`
	Kelurahan        pgtype.Text      `json:"kelurahan"`
	JenisPermohonan  string           `json:"jenisPermohonan"`
	StatusTerkini    pgtype.Text      `json:"statusTerkini"`
	TanggalDaftar    pgtype.Timestamp `json:"tanggalDaftar"`
	JadwalTanggal    pgtype.Date      `json:"jadwalTanggal"`
	JadwalJamMulai   pgtype.Time      `json:"jadwalJamMulai"`
	JadwalJamSelesai pgtype.Time      `json:"jadwalJamSelesai"`
	NomorAntrian     pgtype.Int2      `json:"nomorAntrian"`
	LokasiPermohonan pgtype.Text      `json:"lokasiPermohonan"`
}

func (q *Queries) GetPermohonanDetailAdmin(ctx context.Context, arg GetPermohonanDetailAdminParams) (GetPermohonanDetailAdminRow, error) {
	row := q.db.QueryRow(ctx, getPermohonanDetailAdmin, arg.ID, arg.KelurahanID)
	var i GetPermohonanDetailAdminRow
	err := row.Scan(
		&i.ID,
		&i.KodeBooking,
		&i.Nik,
		&i.NamaLengkap,
		&i.JenisKelamin,
		&i.Alamat,
		&i.NoTelp,
		&i.Kelurahan,
		&i.JenisPermohonan,
		&i.StatusTerkini,
		&i.TanggalDaftar,
		&i.JadwalTanggal,
		&i.JadwalJamMulai,
		&i.JadwalJamSelesai,
		&i.NomorAntrian,
		&i.LokasiPermohonan,
	)
	return i, err
}

const getPetugasStatsAdmin = `-- name: GetPetugasStatsAdmin :one
SELECT 
    COUNT(*) AS total,
    COUNT(*) FILTER (WHERE role = 'ADMIN_KECAMATAN') AS admin_kecamatan,
    COUNT(*) FILTER (WHERE role = 'ADMIN_KELURAHAN') AS admin_kelurahan,
    COUNT(*) FILTER (WHERE is_active = TRUE) AS aktif
FROM petugas
`

type GetPetugasStatsAdminRow struct {
	Total          int64 `json:"total"`
	AdminKecamatan int64 `json:"adminKecamatan"`
	AdminKelurahan int64 `json:"adminKelurahan"`
	Aktif          int64 `json:"aktif"`
}

func (q *Queries) GetPetugasStatsAdmin(ctx context.Context) (GetPetugasStatsAdminRow, error) {
	row := q.db.QueryRow(ctx, getPetugasStatsAdmin)
	var i GetPetugasStatsAdminRow
	err := row.Scan(
		&i.Total,
		&i.AdminKecamatan,
		&i.AdminKelurahan,
		&i.Aktif,
	)
	return i, err
}

const listPendudukAdmin = `-- name: ListPendudukAdmin :many
SELECT 
    p.nik,
    p.nama_lengkap,
    p.jenis_kelamin,
    p.alamat,
    p.email,
    p.no_hp,
    k.nama_kelurahan
FROM penduduk p
LEFT JOIN ref_kelurahan k ON p.kelurahan_id = k.id
WHERE 
    ($1::text IS NULL OR 
     p.nik ILIKE '%' || $1 || '%' OR 
     p.nama_lengkap ILIKE '%' || $1 || '%' OR
     p.alamat ILIKE '%' || $1 || '%')
    AND ($2::smallint IS NULL OR p.kelurahan_id = $2)
ORDER BY p.created_at DESC
`

type ListPendudukAdminParams struct {
	Search      pgtype.Text `json:"search"`
	KelurahanID pgtype.Int2 `json:"kelurahanId"`
}

type ListPendudukAdminRow struct {
	Nik           string      `json:"nik"`
	NamaLengkap   string      `json:"namaLengkap"`
	JenisKelamin  string      `json:"jenisKelamin"`
	Alamat        pgtype.Text `json:"alamat"`
	Email         pgtype.Text `json:"email"`
	NoHp          pgtype.Text `json:"noHp"`
	NamaKelurahan pgtype.Text `json:"namaKelurahan"`
}

func (q *Queries) ListPendudukAdmin(ctx context.Context, arg ListPendudukAdminParams) ([]ListPendudukAdminRow, error) {
	rows, err := q.db.Query(ctx, listPendudukAdmin, arg.Search, arg.KelurahanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendudukAdminRow
	for rows.Next() {
		var i ListPendudukAdminRow
		if err := rows.Scan(
			&i.Nik,
			&i.NamaLengkap,
			&i.JenisKelamin,
			&i.Alamat,
			&i.Email,
			&i.NoHp,
			&i.NamaKelurahan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermohonanAdmin = `-- name: ListPermohonanAdmin :many
SELECT 
    p.id,
    p.kode_booking,
    p.nik,
    pd.nama_lengkap,
    p.jenis_permohonan,
    p.status_terkini,
    p.created_at as tanggal_daftar,
    js.tanggal as jadwal_tanggal,
    js.jam_mulai as jadwal_jam_mulai,
    js.jam_selesai as jadwal_jam_selesai,
    p.nomor_antrian_sesi as nomor_antrian,
    k.id as lokasi_kelurahan_id,
    k.nama_kelurahan as lokasi_nama_kelurahan
FROM permohonan p
JOIN penduduk pd ON p.nik = pd.nik
LEFT JOIN jadwal_sesi js ON p.jadwal_sesi_id = js.id
LEFT JOIN ref_kelurahan k ON js.lokasi_kelurahan_id = k.id
WHERE 
    ($3::text IS NULL OR 
     p.nik ILIKE '%' || $3 || '%' OR 
     p.kode_booking ILIKE '%' || $3 || '%' OR 
     pd.nama_lengkap ILIKE '%' || $3 || '%')
    AND ($4::text IS NULL OR p.status_terkini = $4)
    AND (
        ($5::smallint IS NOT NULL AND js.lokasi_kelurahan_id = $5)
        OR
        ($5::smallint IS NULL AND js.lokasi_kelurahan_id IS NULL)
    )
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPermohonanAdminParams struct {
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
	Search      pgtype.Text `json:"search"`
	Status      pgtype.Text `json:"status"`
	KelurahanID pgtype.Int2 `json:"kelurahanId"`
}

type ListPermohonanAdminRow struct {
	ID                  uuid.UUID        `json:"id"`
	KodeBooking         pgtype.Text      `json:"kodeBooking"`
	Nik                 pgtype.Text      `json:"nik"`
	NamaLengkap         string           `json:"namaLengkap"`
	JenisPermohonan     string           `json:"jenisPermohonan"`
	StatusTerkini       pgtype.Text      `json:"statusTerkini"`
	TanggalDaftar       pgtype.Timestamp `json:"tanggalDaftar"`
	JadwalTanggal       pgtype.Date      `json:"jadwalTanggal"`
	JadwalJamMulai      pgtype.Time      `json:"jadwalJamMulai"`
	JadwalJamSelesai    pgtype.Time      `json:"jadwalJamSelesai"`
	NomorAntrian        pgtype.Int2      `json:"nomorAntrian"`
	LokasiKelurahanID   pgtype.Int2      `json:"lokasiKelurahanId"`
	LokasiNamaKelurahan pgtype.Text      `json:"lokasiNamaKelurahan"`
}

func (q *Queries) ListPermohonanAdmin(ctx context.Context, arg ListPermohonanAdminParams) ([]ListPermohonanAdminRow, error) {
	rows, err := q.db.Query(ctx, listPermohonanAdmin,
		arg.Limit,
		arg.Offset,
		arg.Search,
		arg.Status,
		arg.KelurahanID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermohonanAdminRow
	for rows.Next() {
		var i ListPermohonanAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.KodeBooking,
			&i.Nik,
			&i.NamaLengkap,
			&i.JenisPermohonan,
			&i.StatusTerkini,
			&i.TanggalDaftar,
			&i.JadwalTanggal,
			&i.JadwalJamMulai,
			&i.JadwalJamSelesai,
			&i.NomorAntrian,
			&i.LokasiKelurahanID,
			&i.LokasiNamaKelurahan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPetugasAdmin = `-- name: ListPetugasAdmin :many
SELECT 
    p.id,
    p.username,
    p.nama_petugas,
    p.nip,
    p.role,
    p.is_active,
    CASE WHEN p.is_active THEN 'AKTIF' ELSE 'NON_AKTIF' END AS status,
    k.nama_kelurahan
FROM petugas p
LEFT JOIN ref_kelurahan k ON p.kelurahan_id = k.id
ORDER BY p.created_at DESC
`

type ListPetugasAdminRow struct {
	ID            uuid.UUID   `json:"id"`
	Username      string      `json:"username"`
	NamaPetugas   string      `json:"namaPetugas"`
	Nip           pgtype.Text `json:"nip"`
	Role          string      `json:"role"`
	IsActive      pgtype.Bool `json:"isActive"`
	Status        string      `json:"status"`
	NamaKelurahan pgtype.Text `json:"namaKelurahan"`
}

func (q *Queries) ListPetugasAdmin(ctx context.Context) ([]ListPetugasAdminRow, error) {
	rows, err := q.db.Query(ctx, listPetugasAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPetugasAdminRow
	for rows.Next() {
		var i ListPetugasAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.NamaPetugas,
			&i.Nip,
			&i.Role,
			&i.IsActive,
			&i.Status,
			&i.NamaKelurahan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodayJadwal = `-- name: ListTodayJadwal :many
SELECT 
    js.id,
    js.tanggal,
    js.jam_mulai,
    js.jam_selesai,
    js.kuota_terisi,
    js.kuota_maksimal,
    js.status_sesi,
    COALESCE(k.nama_kelurahan, 'Kecamatan Pademangan')::text as nama_kelurahan
FROM jadwal_sesi js
LEFT JOIN ref_kelurahan k ON js.lokasi_kelurahan_id = k.id
WHERE js.tanggal = CURRENT_DATE
  AND (
    ($1::smallint IS NOT NULL AND js.lokasi_kelurahan_id = $1)
    OR
    ($1::smallint IS NULL AND js.lokasi_kelurahan_id IS NULL)
  )
ORDER BY js.jam_mulai
`

type ListTodayJadwalRow struct {
	ID            uuid.UUID   `json:"id"`
	Tanggal       pgtype.Date `json:"tanggal"`
	JamMulai      pgtype.Time `json:"jamMulai"`
	JamSelesai    pgtype.Time `json:"jamSelesai"`
	KuotaTerisi   int16       `json:"kuotaTerisi"`
	KuotaMaksimal int16       `json:"kuotaMaksimal"`
	StatusSesi    pgtype.Text `json:"statusSesi"`
	NamaKelurahan string      `json:"namaKelurahan"`
}

func (q *Queries) ListTodayJadwal(ctx context.Context, kelurahanID pgtype.Int2) ([]ListTodayJadwalRow, error) {
	rows, err := q.db.Query(ctx, listTodayJadwal, kelurahanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTodayJadwalRow
	for rows.Next() {
		var i ListTodayJadwalRow
		if err := rows.Scan(
			&i.ID,
			&i.Tanggal,
			&i.JamMulai,
			&i.JamSelesai,
			&i.KuotaTerisi,
			&i.KuotaMaksimal,
			&i.StatusSesi,
			&i.NamaKelurahan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermohonanStatusAdmin = `-- name: UpdatePermohonanStatusAdmin :exec
UPDATE permohonan p
SET status_terkini = $2
FROM jadwal_sesi js
WHERE p.id = $1
  AND p.jadwal_sesi_id = js.id
  AND (
    ($3::smallint IS NOT NULL AND js.lokasi_kelurahan_id = $3)
    OR
    ($3::smallint IS NULL AND js.lokasi_kelurahan_id IS NULL)
  )
`

type UpdatePermohonanStatusAdminParams struct {
	ID            uuid.UUID   `json:"id"`
	StatusTerkini pgtype.Text `json:"statusTerkini"`
	KelurahanID   pgtype.Int2 `json:"kelurahanId"`
}

func (q *Queries) UpdatePermohonanStatusAdmin(ctx context.Context, arg UpdatePermohonanStatusAdminParams) error {
	_, err := q.db.Exec(ctx, updatePermohonanStatusAdmin, arg.ID, arg.StatusTerkini, arg.KelurahanID)
	return err
}
