// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package pg_store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(SELECT 1 FROM penduduk WHERE email = $1) AS exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkPendudukExists = `-- name: CheckPendudukExists :one
SELECT EXISTS(SELECT 1 FROM penduduk WHERE nik = $1) AS exists
`

func (q *Queries) CheckPendudukExists(ctx context.Context, nik string) (bool, error) {
	row := q.db.QueryRow(ctx, checkPendudukExists, nik)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createPenduduk = `-- name: CreatePenduduk :one
INSERT INTO penduduk (
    nik,
    kelurahan_id,
    email,
    password_hash,
    nama_lengkap,
    alamat,
    no_hp,
    jenis_kelamin
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING nik, kelurahan_id, email, password_hash, nama_lengkap, alamat, no_hp, created_at, jenis_kelamin
`

type CreatePendudukParams struct {
	Nik          string      `json:"nik"`
	KelurahanID  pgtype.Int2 `json:"kelurahanId"`
	Email        pgtype.Text `json:"email"`
	PasswordHash pgtype.Text `json:"passwordHash"`
	NamaLengkap  string      `json:"namaLengkap"`
	Alamat       pgtype.Text `json:"alamat"`
	NoHp         pgtype.Text `json:"noHp"`
	JenisKelamin string      `json:"jenisKelamin"`
}

func (q *Queries) CreatePenduduk(ctx context.Context, arg CreatePendudukParams) (Penduduk, error) {
	row := q.db.QueryRow(ctx, createPenduduk,
		arg.Nik,
		arg.KelurahanID,
		arg.Email,
		arg.PasswordHash,
		arg.NamaLengkap,
		arg.Alamat,
		arg.NoHp,
		arg.JenisKelamin,
	)
	var i Penduduk
	err := row.Scan(
		&i.Nik,
		&i.KelurahanID,
		&i.Email,
		&i.PasswordHash,
		&i.NamaLengkap,
		&i.Alamat,
		&i.NoHp,
		&i.CreatedAt,
		&i.JenisKelamin,
	)
	return i, err
}

const getPendudukByNIK = `-- name: GetPendudukByNIK :one
SELECT nik, kelurahan_id, email, password_hash, nama_lengkap, alamat, no_hp, created_at, jenis_kelamin FROM penduduk WHERE nik = $1
`

func (q *Queries) GetPendudukByNIK(ctx context.Context, nik string) (Penduduk, error) {
	row := q.db.QueryRow(ctx, getPendudukByNIK, nik)
	var i Penduduk
	err := row.Scan(
		&i.Nik,
		&i.KelurahanID,
		&i.Email,
		&i.PasswordHash,
		&i.NamaLengkap,
		&i.Alamat,
		&i.NoHp,
		&i.CreatedAt,
		&i.JenisKelamin,
	)
	return i, err
}

const getPetugasByNIP = `-- name: GetPetugasByNIP :one
SELECT id, kelurahan_id, nip, nama_petugas, created_by, username, password_hash, is_active, created_at, role FROM petugas WHERE nip = $1 AND is_active = TRUE
`

func (q *Queries) GetPetugasByNIP(ctx context.Context, nip pgtype.Text) (Petugas, error) {
	row := q.db.QueryRow(ctx, getPetugasByNIP, nip)
	var i Petugas
	err := row.Scan(
		&i.ID,
		&i.KelurahanID,
		&i.Nip,
		&i.NamaPetugas,
		&i.CreatedBy,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}
