// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jadwal.sql

package pg_store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPermohonanByJadwal = `-- name: CountPermohonanByJadwal :one
SELECT COUNT(*) as count
FROM permohonan
WHERE jadwal_sesi_id = $1
`

func (q *Queries) CountPermohonanByJadwal(ctx context.Context, jadwalSesiID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPermohonanByJadwal, jadwalSesiID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJadwalSesi = `-- name: CreateJadwalSesi :one
INSERT INTO jadwal_sesi (
    lokasi_kelurahan_id,
    tanggal,
    jam_mulai,
    jam_selesai,
    kuota_maksimal,
    kuota_terisi,
    status_sesi
) VALUES ($1, $2, $3, $4, $5, 0, 'BUKA')
ON CONFLICT (tanggal, jam_mulai, lokasi_kelurahan_id) DO NOTHING
RETURNING id
`

type CreateJadwalSesiParams struct {
	LokasiKelurahanID pgtype.Int2 `json:"lokasiKelurahanId"`
	Tanggal           pgtype.Date `json:"tanggal"`
	JamMulai          pgtype.Time `json:"jamMulai"`
	JamSelesai        pgtype.Time `json:"jamSelesai"`
	KuotaMaksimal     int16       `json:"kuotaMaksimal"`
}

func (q *Queries) CreateJadwalSesi(ctx context.Context, arg CreateJadwalSesiParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createJadwalSesi,
		arg.LokasiKelurahanID,
		arg.Tanggal,
		arg.JamMulai,
		arg.JamSelesai,
		arg.KuotaMaksimal,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteJadwalSesi = `-- name: DeleteJadwalSesi :exec
DELETE FROM jadwal_sesi
WHERE id = $1
  AND (
    ($2::integer IS NOT NULL AND lokasi_kelurahan_id = $2)
    OR
    ($2::integer IS NULL AND lokasi_kelurahan_id IS NULL)
  )
`

type DeleteJadwalSesiParams struct {
	ID          uuid.UUID   `json:"id"`
	KelurahanID pgtype.Int4 `json:"kelurahanId"`
}

func (q *Queries) DeleteJadwalSesi(ctx context.Context, arg DeleteJadwalSesiParams) error {
	_, err := q.db.Exec(ctx, deleteJadwalSesi, arg.ID, arg.KelurahanID)
	return err
}

const getJadwalSesiById = `-- name: GetJadwalSesiById :one
SELECT 
    js.id,
    js.tanggal,
    js.jam_mulai,
    js.jam_selesai,
    js.kuota_terisi,
    js.kuota_maksimal,
    js.status_sesi,
    js.lokasi_kelurahan_id,
    COALESCE(k.nama_kelurahan, 'Kecamatan Pademangan')::text as nama_kelurahan
FROM jadwal_sesi js
LEFT JOIN ref_kelurahan k ON js.lokasi_kelurahan_id = k.id
WHERE js.id = $1
`

type GetJadwalSesiByIdRow struct {
	ID                uuid.UUID   `json:"id"`
	Tanggal           pgtype.Date `json:"tanggal"`
	JamMulai          pgtype.Time `json:"jamMulai"`
	JamSelesai        pgtype.Time `json:"jamSelesai"`
	KuotaTerisi       int16       `json:"kuotaTerisi"`
	KuotaMaksimal     int16       `json:"kuotaMaksimal"`
	StatusSesi        pgtype.Text `json:"statusSesi"`
	LokasiKelurahanID pgtype.Int2 `json:"lokasiKelurahanId"`
	NamaKelurahan     string      `json:"namaKelurahan"`
}

func (q *Queries) GetJadwalSesiById(ctx context.Context, id uuid.UUID) (GetJadwalSesiByIdRow, error) {
	row := q.db.QueryRow(ctx, getJadwalSesiById, id)
	var i GetJadwalSesiByIdRow
	err := row.Scan(
		&i.ID,
		&i.Tanggal,
		&i.JamMulai,
		&i.JamSelesai,
		&i.KuotaTerisi,
		&i.KuotaMaksimal,
		&i.StatusSesi,
		&i.LokasiKelurahanID,
		&i.NamaKelurahan,
	)
	return i, err
}

const getKelurahanById = `-- name: GetKelurahanById :one
SELECT id, nama_kelurahan
FROM ref_kelurahan
WHERE id = $1
`

type GetKelurahanByIdRow struct {
	ID            int16  `json:"id"`
	NamaKelurahan string `json:"namaKelurahan"`
}

func (q *Queries) GetKelurahanById(ctx context.Context, id int16) (GetKelurahanByIdRow, error) {
	row := q.db.QueryRow(ctx, getKelurahanById, id)
	var i GetKelurahanByIdRow
	err := row.Scan(&i.ID, &i.NamaKelurahan)
	return i, err
}

const incrementKuotaTerisi = `-- name: IncrementKuotaTerisi :exec
UPDATE jadwal_sesi
SET kuota_terisi = kuota_terisi + 1
WHERE id = $1 AND kuota_terisi < kuota_maksimal
`

func (q *Queries) IncrementKuotaTerisi(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementKuotaTerisi, id)
	return err
}

const listAllKelurahan = `-- name: ListAllKelurahan :many
SELECT id, nama_kelurahan
FROM ref_kelurahan
ORDER BY nama_kelurahan
`

type ListAllKelurahanRow struct {
	ID            int16  `json:"id"`
	NamaKelurahan string `json:"namaKelurahan"`
}

func (q *Queries) ListAllKelurahan(ctx context.Context) ([]ListAllKelurahanRow, error) {
	rows, err := q.db.Query(ctx, listAllKelurahan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllKelurahanRow
	for rows.Next() {
		var i ListAllKelurahanRow
		if err := rows.Scan(&i.ID, &i.NamaKelurahan); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJadwalSesi = `-- name: ListJadwalSesi :many
SELECT 
    js.id,
    js.tanggal,
    js.jam_mulai,
    js.jam_selesai,
    js.kuota_terisi,
    js.kuota_maksimal,
    js.status_sesi,
    COALESCE(k.nama_kelurahan, 'Kecamatan Pademangan')::text as nama_kelurahan
FROM jadwal_sesi js
LEFT JOIN ref_kelurahan k ON js.lokasi_kelurahan_id = k.id
WHERE js.tanggal >= $1 AND js.tanggal <= $2
  AND (
    ($3::integer IS NOT NULL AND js.lokasi_kelurahan_id = $3)
    OR
    ($3::integer IS NULL AND js.lokasi_kelurahan_id IS NULL)
  )
ORDER BY js.tanggal, js.jam_mulai
`

type ListJadwalSesiParams struct {
	Tanggal     pgtype.Date `json:"tanggal"`
	Tanggal_2   pgtype.Date `json:"tanggal2"`
	KelurahanID pgtype.Int4 `json:"kelurahanId"`
}

type ListJadwalSesiRow struct {
	ID            uuid.UUID   `json:"id"`
	Tanggal       pgtype.Date `json:"tanggal"`
	JamMulai      pgtype.Time `json:"jamMulai"`
	JamSelesai    pgtype.Time `json:"jamSelesai"`
	KuotaTerisi   int16       `json:"kuotaTerisi"`
	KuotaMaksimal int16       `json:"kuotaMaksimal"`
	StatusSesi    pgtype.Text `json:"statusSesi"`
	NamaKelurahan string      `json:"namaKelurahan"`
}

func (q *Queries) ListJadwalSesi(ctx context.Context, arg ListJadwalSesiParams) ([]ListJadwalSesiRow, error) {
	rows, err := q.db.Query(ctx, listJadwalSesi, arg.Tanggal, arg.Tanggal_2, arg.KelurahanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJadwalSesiRow
	for rows.Next() {
		var i ListJadwalSesiRow
		if err := rows.Scan(
			&i.ID,
			&i.Tanggal,
			&i.JamMulai,
			&i.JamSelesai,
			&i.KuotaTerisi,
			&i.KuotaMaksimal,
			&i.StatusSesi,
			&i.NamaKelurahan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermohonanByJadwal = `-- name: ListPermohonanByJadwal :many
SELECT 
    p.id,
    p.kode_booking,
    p.nik,
    pd.nama_lengkap,
    p.status_terkini,
    p.nomor_antrian_sesi as nomor_antrian
FROM permohonan p
JOIN penduduk pd ON p.nik = pd.nik
WHERE p.jadwal_sesi_id = $1
ORDER BY p.nomor_antrian_sesi ASC
`

type ListPermohonanByJadwalRow struct {
	ID            uuid.UUID   `json:"id"`
	KodeBooking   pgtype.Text `json:"kodeBooking"`
	Nik           pgtype.Text `json:"nik"`
	NamaLengkap   string      `json:"namaLengkap"`
	StatusTerkini pgtype.Text `json:"statusTerkini"`
	NomorAntrian  pgtype.Int2 `json:"nomorAntrian"`
}

func (q *Queries) ListPermohonanByJadwal(ctx context.Context, jadwalSesiID pgtype.UUID) ([]ListPermohonanByJadwalRow, error) {
	rows, err := q.db.Query(ctx, listPermohonanByJadwal, jadwalSesiID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermohonanByJadwalRow
	for rows.Next() {
		var i ListPermohonanByJadwalRow
		if err := rows.Scan(
			&i.ID,
			&i.KodeBooking,
			&i.Nik,
			&i.NamaLengkap,
			&i.StatusTerkini,
			&i.NomorAntrian,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJadwalSesi = `-- name: UpdateJadwalSesi :exec
UPDATE jadwal_sesi
SET 
    tanggal = $2,
    jam_mulai = $3,
    jam_selesai = $4,
    kuota_maksimal = $5,
    status_sesi = $6
WHERE id = $1
`

type UpdateJadwalSesiParams struct {
	ID            uuid.UUID   `json:"id"`
	Tanggal       pgtype.Date `json:"tanggal"`
	JamMulai      pgtype.Time `json:"jamMulai"`
	JamSelesai    pgtype.Time `json:"jamSelesai"`
	KuotaMaksimal int16       `json:"kuotaMaksimal"`
	StatusSesi    pgtype.Text `json:"statusSesi"`
}

func (q *Queries) UpdateJadwalSesi(ctx context.Context, arg UpdateJadwalSesiParams) error {
	_, err := q.db.Exec(ctx, updateJadwalSesi,
		arg.ID,
		arg.Tanggal,
		arg.JamMulai,
		arg.JamSelesai,
		arg.KuotaMaksimal,
		arg.StatusSesi,
	)
	return err
}
