// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permohonan.sql

package pg_store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPermohonanByStatus = `-- name: CountPermohonanByStatus :one
SELECT 
    COUNT(*) FILTER (WHERE status_terkini = 'VERIFIKASI') as verifikasi,
    COUNT(*) FILTER (WHERE status_terkini = 'PROSES') as proses,
    COUNT(*) FILTER (WHERE status_terkini = 'SIAP_AMBIL') as siap_ambil,
    COUNT(*) FILTER (WHERE status_terkini = 'SELESAI') as selesai,
    COUNT(*) FILTER (WHERE status_terkini = 'DITOLAK') as ditolak,
    COUNT(*) as total
FROM permohonan
`

type CountPermohonanByStatusRow struct {
	Verifikasi int64 `json:"verifikasi"`
	Proses     int64 `json:"proses"`
	SiapAmbil  int64 `json:"siapAmbil"`
	Selesai    int64 `json:"selesai"`
	Ditolak    int64 `json:"ditolak"`
	Total      int64 `json:"total"`
}

func (q *Queries) CountPermohonanByStatus(ctx context.Context) (CountPermohonanByStatusRow, error) {
	row := q.db.QueryRow(ctx, countPermohonanByStatus)
	var i CountPermohonanByStatusRow
	err := row.Scan(
		&i.Verifikasi,
		&i.Proses,
		&i.SiapAmbil,
		&i.Selesai,
		&i.Ditolak,
		&i.Total,
	)
	return i, err
}

const createDokumenSyarat = `-- name: CreateDokumenSyarat :exec
INSERT INTO dokumen_syarat (
    permohonan_id,
    file_path,
    jenis_dokumen
) VALUES ($1, $2, $3)
`

type CreateDokumenSyaratParams struct {
	PermohonanID pgtype.UUID `json:"permohonanId"`
	FilePath     string      `json:"filePath"`
	JenisDokumen string      `json:"jenisDokumen"`
}

func (q *Queries) CreateDokumenSyarat(ctx context.Context, arg CreateDokumenSyaratParams) error {
	_, err := q.db.Exec(ctx, createDokumenSyarat, arg.PermohonanID, arg.FilePath, arg.JenisDokumen)
	return err
}

const createPermohonan = `-- name: CreatePermohonan :one
INSERT INTO permohonan (
    nik,
    jadwal_sesi_id,
    jenis_permohonan
) VALUES ($1, $2, $3)
RETURNING id
`

type CreatePermohonanParams struct {
	Nik             pgtype.Text `json:"nik"`
	JadwalSesiID    pgtype.UUID `json:"jadwalSesiId"`
	JenisPermohonan string      `json:"jenisPermohonan"`
}

func (q *Queries) CreatePermohonan(ctx context.Context, arg CreatePermohonanParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPermohonan, arg.Nik, arg.JadwalSesiID, arg.JenisPermohonan)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getPermohonanDetail = `-- name: GetPermohonanDetail :one
SELECT 
    p.id,
    p.kode_booking,
    p.jenis_permohonan,
    p.status_terkini,
    p.nomor_antrian_sesi as nomor_antrian,
    p.created_at,
    pd.nik,
    pd.nama_lengkap,
    pd.jenis_kelamin,
    pd.alamat,
    pd.no_hp,
    k.nama_kelurahan,
    js.tanggal as jadwal_tanggal,
    js.jam_mulai as jadwal_jam_mulai,
    js.jam_selesai as jadwal_jam_selesai
FROM permohonan p
JOIN penduduk pd ON p.nik = pd.nik
LEFT JOIN ref_kelurahan k ON pd.kelurahan_id = k.id
LEFT JOIN jadwal_sesi js ON p.jadwal_sesi_id = js.id
WHERE p.id = $1
`

type GetPermohonanDetailRow struct {
	ID               uuid.UUID        `json:"id"`
	KodeBooking      pgtype.Text      `json:"kodeBooking"`
	JenisPermohonan  string           `json:"jenisPermohonan"`
	StatusTerkini    pgtype.Text      `json:"statusTerkini"`
	NomorAntrian     pgtype.Int2      `json:"nomorAntrian"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	Nik              string           `json:"nik"`
	NamaLengkap      string           `json:"namaLengkap"`
	JenisKelamin     string           `json:"jenisKelamin"`
	Alamat           pgtype.Text      `json:"alamat"`
	NoHp             pgtype.Text      `json:"noHp"`
	NamaKelurahan    pgtype.Text      `json:"namaKelurahan"`
	JadwalTanggal    pgtype.Date      `json:"jadwalTanggal"`
	JadwalJamMulai   pgtype.Time      `json:"jadwalJamMulai"`
	JadwalJamSelesai pgtype.Time      `json:"jadwalJamSelesai"`
}

func (q *Queries) GetPermohonanDetail(ctx context.Context, id uuid.UUID) (GetPermohonanDetailRow, error) {
	row := q.db.QueryRow(ctx, getPermohonanDetail, id)
	var i GetPermohonanDetailRow
	err := row.Scan(
		&i.ID,
		&i.KodeBooking,
		&i.JenisPermohonan,
		&i.StatusTerkini,
		&i.NomorAntrian,
		&i.CreatedAt,
		&i.Nik,
		&i.NamaLengkap,
		&i.JenisKelamin,
		&i.Alamat,
		&i.NoHp,
		&i.NamaKelurahan,
		&i.JadwalTanggal,
		&i.JadwalJamMulai,
		&i.JadwalJamSelesai,
	)
	return i, err
}

const getPermohonanStatusById = `-- name: GetPermohonanStatusById :one
SELECT 
    p.id,
    p.status_terkini
FROM permohonan p
WHERE p.id = $1
`

type GetPermohonanStatusByIdRow struct {
	ID            uuid.UUID   `json:"id"`
	StatusTerkini pgtype.Text `json:"statusTerkini"`
}

func (q *Queries) GetPermohonanStatusById(ctx context.Context, id uuid.UUID) (GetPermohonanStatusByIdRow, error) {
	row := q.db.QueryRow(ctx, getPermohonanStatusById, id)
	var i GetPermohonanStatusByIdRow
	err := row.Scan(&i.ID, &i.StatusTerkini)
	return i, err
}

const getRiwayatStatusByPermohonan = `-- name: GetRiwayatStatusByPermohonan :many
SELECT 
    rs.status_baru,
    rs.catatan_proses,
    rs.waktu_proses,
    pt.nama_petugas
FROM riwayat_status rs
LEFT JOIN petugas pt ON rs.petugas_id = pt.id
WHERE rs.permohonan_id = $1
ORDER BY rs.waktu_proses DESC
`

type GetRiwayatStatusByPermohonanRow struct {
	StatusBaru    string           `json:"statusBaru"`
	CatatanProses pgtype.Text      `json:"catatanProses"`
	WaktuProses   pgtype.Timestamp `json:"waktuProses"`
	NamaPetugas   pgtype.Text      `json:"namaPetugas"`
}

func (q *Queries) GetRiwayatStatusByPermohonan(ctx context.Context, permohonanID pgtype.UUID) ([]GetRiwayatStatusByPermohonanRow, error) {
	rows, err := q.db.Query(ctx, getRiwayatStatusByPermohonan, permohonanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRiwayatStatusByPermohonanRow
	for rows.Next() {
		var i GetRiwayatStatusByPermohonanRow
		if err := rows.Scan(
			&i.StatusBaru,
			&i.CatatanProses,
			&i.WaktuProses,
			&i.NamaPetugas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRiwayatStatus = `-- name: InsertRiwayatStatus :exec
INSERT INTO riwayat_status (
    permohonan_id,
    petugas_id,
    status_baru,
    catatan_proses,
    waktu_proses
) VALUES ($1, $2, $3, $4, NOW())
`

type InsertRiwayatStatusParams struct {
	PermohonanID  pgtype.UUID `json:"permohonanId"`
	PetugasID     pgtype.UUID `json:"petugasId"`
	StatusBaru    string      `json:"statusBaru"`
	CatatanProses pgtype.Text `json:"catatanProses"`
}

func (q *Queries) InsertRiwayatStatus(ctx context.Context, arg InsertRiwayatStatusParams) error {
	_, err := q.db.Exec(ctx, insertRiwayatStatus,
		arg.PermohonanID,
		arg.PetugasID,
		arg.StatusBaru,
		arg.CatatanProses,
	)
	return err
}

const listPermohonanByStatus = `-- name: ListPermohonanByStatus :many
SELECT 
    p.id,
    p.kode_booking,
    pd.nik,
    pd.nama_lengkap,
    p.jenis_permohonan,
    p.status_terkini,
    p.created_at as tanggal_daftar,
    js.tanggal as jadwal_tanggal,
    js.jam_mulai as jadwal_jam,
    p.nomor_antrian_sesi as nomor_antrian
FROM permohonan p
JOIN penduduk pd ON p.nik = pd.nik
LEFT JOIN jadwal_sesi js ON p.jadwal_sesi_id = js.id
WHERE ($1::text IS NULL OR p.status_terkini = $1)
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPermohonanByStatusParams struct {
	Column1 string `json:"column1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListPermohonanByStatusRow struct {
	ID              uuid.UUID        `json:"id"`
	KodeBooking     pgtype.Text      `json:"kodeBooking"`
	Nik             string           `json:"nik"`
	NamaLengkap     string           `json:"namaLengkap"`
	JenisPermohonan string           `json:"jenisPermohonan"`
	StatusTerkini   pgtype.Text      `json:"statusTerkini"`
	TanggalDaftar   pgtype.Timestamp `json:"tanggalDaftar"`
	JadwalTanggal   pgtype.Date      `json:"jadwalTanggal"`
	JadwalJam       pgtype.Time      `json:"jadwalJam"`
	NomorAntrian    pgtype.Int2      `json:"nomorAntrian"`
}

func (q *Queries) ListPermohonanByStatus(ctx context.Context, arg ListPermohonanByStatusParams) ([]ListPermohonanByStatusRow, error) {
	rows, err := q.db.Query(ctx, listPermohonanByStatus, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermohonanByStatusRow
	for rows.Next() {
		var i ListPermohonanByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.KodeBooking,
			&i.Nik,
			&i.NamaLengkap,
			&i.JenisPermohonan,
			&i.StatusTerkini,
			&i.TanggalDaftar,
			&i.JadwalTanggal,
			&i.JadwalJam,
			&i.NomorAntrian,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermohonanStatus = `-- name: UpdatePermohonanStatus :exec
UPDATE permohonan
SET status_terkini = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePermohonanStatusParams struct {
	ID            uuid.UUID   `json:"id"`
	StatusTerkini pgtype.Text `json:"statusTerkini"`
}

func (q *Queries) UpdatePermohonanStatus(ctx context.Context, arg UpdatePermohonanStatusParams) error {
	_, err := q.db.Exec(ctx, updatePermohonanStatus, arg.ID, arg.StatusTerkini)
	return err
}
