// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pg_store

import (
	"context"
)

type Querier interface {
	CheckHealth(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
