// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seed.sql

package pg_store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKelurahan = `-- name: CreateKelurahan :one
INSERT INTO ref_kelurahan (nama_kelurahan, kode_area)
VALUES ($1, $2)
RETURNING id, nama_kelurahan, kode_area, created_at
`

type CreateKelurahanParams struct {
	NamaKelurahan string `json:"namaKelurahan"`
	KodeArea      string `json:"kodeArea"`
}

func (q *Queries) CreateKelurahan(ctx context.Context, arg CreateKelurahanParams) (RefKelurahan, error) {
	row := q.db.QueryRow(ctx, createKelurahan, arg.NamaKelurahan, arg.KodeArea)
	var i RefKelurahan
	err := row.Scan(
		&i.ID,
		&i.NamaKelurahan,
		&i.KodeArea,
		&i.CreatedAt,
	)
	return i, err
}

const createPetugas = `-- name: CreatePetugas :one
INSERT INTO petugas (kelurahan_id, nip, nama_petugas, created_by, username, password_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, kelurahan_id, nip, nama_petugas, created_by, username, password_hash, is_active, created_at, role
`

type CreatePetugasParams struct {
	KelurahanID  pgtype.Int2 `json:"kelurahanId"`
	Nip          pgtype.Text `json:"nip"`
	NamaPetugas  string      `json:"namaPetugas"`
	CreatedBy    pgtype.UUID `json:"createdBy"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"passwordHash"`
}

func (q *Queries) CreatePetugas(ctx context.Context, arg CreatePetugasParams) (Petugas, error) {
	row := q.db.QueryRow(ctx, createPetugas,
		arg.KelurahanID,
		arg.Nip,
		arg.NamaPetugas,
		arg.CreatedBy,
		arg.Username,
		arg.PasswordHash,
	)
	var i Petugas
	err := row.Scan(
		&i.ID,
		&i.KelurahanID,
		&i.Nip,
		&i.NamaPetugas,
		&i.CreatedBy,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const getKelurahanByKodeArea = `-- name: GetKelurahanByKodeArea :one
SELECT id, nama_kelurahan, kode_area, created_at FROM ref_kelurahan WHERE kode_area = $1
`

func (q *Queries) GetKelurahanByKodeArea(ctx context.Context, kodeArea string) (RefKelurahan, error) {
	row := q.db.QueryRow(ctx, getKelurahanByKodeArea, kodeArea)
	var i RefKelurahan
	err := row.Scan(
		&i.ID,
		&i.NamaKelurahan,
		&i.KodeArea,
		&i.CreatedAt,
	)
	return i, err
}

const getPetugasByUsername = `-- name: GetPetugasByUsername :one
SELECT id, kelurahan_id, nip, nama_petugas, created_by, username, password_hash, is_active, created_at, role FROM petugas WHERE username = $1
`

func (q *Queries) GetPetugasByUsername(ctx context.Context, username string) (Petugas, error) {
	row := q.db.QueryRow(ctx, getPetugasByUsername, username)
	var i Petugas
	err := row.Scan(
		&i.ID,
		&i.KelurahanID,
		&i.Nip,
		&i.NamaPetugas,
		&i.CreatedBy,
		&i.Username,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.Role,
	)
	return i, err
}

const listKelurahan = `-- name: ListKelurahan :many
SELECT id, nama_kelurahan, kode_area, created_at FROM ref_kelurahan ORDER BY id
`

func (q *Queries) ListKelurahan(ctx context.Context) ([]RefKelurahan, error) {
	rows, err := q.db.Query(ctx, listKelurahan)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefKelurahan
	for rows.Next() {
		var i RefKelurahan
		if err := rows.Scan(
			&i.ID,
			&i.NamaKelurahan,
			&i.KodeArea,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateSeedTables = `-- name: TruncateSeedTables :exec
TRUNCATE riwayat_status, dokumen_syarat, permohonan, jadwal_sesi, petugas, penduduk, ref_kelurahan RESTART IDENTITY CASCADE
`

func (q *Queries) TruncateSeedTables(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateSeedTables)
	return err
}
