// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package pg_store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPermohonanByNIK = `-- name: CountPermohonanByNIK :one
SELECT 
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE status_terkini = 'VERIFIKASI') as verifikasi,
    COUNT(*) FILTER (WHERE status_terkini = 'PROSES') as proses,
    COUNT(*) FILTER (WHERE status_terkini = 'SIAP_AMBIL') as siap_ambil,
    COUNT(*) FILTER (WHERE status_terkini = 'SELESAI') as selesai,
    COUNT(*) FILTER (WHERE status_terkini = 'DITOLAK') as ditolak
FROM permohonan 
WHERE nik = $1
`

type CountPermohonanByNIKRow struct {
	Total      int64 `json:"total"`
	Verifikasi int64 `json:"verifikasi"`
	Proses     int64 `json:"proses"`
	SiapAmbil  int64 `json:"siapAmbil"`
	Selesai    int64 `json:"selesai"`
	Ditolak    int64 `json:"ditolak"`
}

func (q *Queries) CountPermohonanByNIK(ctx context.Context, nik pgtype.Text) (CountPermohonanByNIKRow, error) {
	row := q.db.QueryRow(ctx, countPermohonanByNIK, nik)
	var i CountPermohonanByNIKRow
	err := row.Scan(
		&i.Total,
		&i.Verifikasi,
		&i.Proses,
		&i.SiapAmbil,
		&i.Selesai,
		&i.Ditolak,
	)
	return i, err
}

const getPendudukProfile = `-- name: GetPendudukProfile :one
SELECT 
    p.nik,
    p.nama_lengkap,
    p.email,
    p.alamat,
    p.no_hp,
    p.jenis_kelamin,
    p.created_at,
    k.nama_kelurahan
FROM penduduk p
LEFT JOIN ref_kelurahan k ON p.kelurahan_id = k.id
WHERE p.nik = $1
`

type GetPendudukProfileRow struct {
	Nik           string           `json:"nik"`
	NamaLengkap   string           `json:"namaLengkap"`
	Email         pgtype.Text      `json:"email"`
	Alamat        pgtype.Text      `json:"alamat"`
	NoHp          pgtype.Text      `json:"noHp"`
	JenisKelamin  string           `json:"jenisKelamin"`
	CreatedAt     pgtype.Timestamp `json:"createdAt"`
	NamaKelurahan pgtype.Text      `json:"namaKelurahan"`
}

func (q *Queries) GetPendudukProfile(ctx context.Context, nik string) (GetPendudukProfileRow, error) {
	row := q.db.QueryRow(ctx, getPendudukProfile, nik)
	var i GetPendudukProfileRow
	err := row.Scan(
		&i.Nik,
		&i.NamaLengkap,
		&i.Email,
		&i.Alamat,
		&i.NoHp,
		&i.JenisKelamin,
		&i.CreatedAt,
		&i.NamaKelurahan,
	)
	return i, err
}

const getPermohonanByKodeBooking = `-- name: GetPermohonanByKodeBooking :one
SELECT 
    p.id,
    p.kode_booking,
    p.jenis_permohonan,
    p.status_terkini,
    p.created_at as tanggal_daftar,
    p.nomor_antrian_sesi as nomor_antrian,
    js.tanggal as jadwal_tanggal,
    js.jam_mulai as jadwal_jam_mulai,
    js.jam_selesai as jadwal_jam_selesai,
    k.nama_kelurahan as lokasi_kelurahan,
    pd.nama_lengkap
FROM permohonan p
LEFT JOIN penduduk pd ON p.nik = pd.nik
LEFT JOIN jadwal_sesi js ON p.jadwal_sesi_id = js.id
LEFT JOIN ref_kelurahan k ON js.lokasi_kelurahan_id = k.id
WHERE p.kode_booking = $1
`

type GetPermohonanByKodeBookingRow struct {
	ID               uuid.UUID        `json:"id"`
	KodeBooking      pgtype.Text      `json:"kodeBooking"`
	JenisPermohonan  string           `json:"jenisPermohonan"`
	StatusTerkini    pgtype.Text      `json:"statusTerkini"`
	TanggalDaftar    pgtype.Timestamp `json:"tanggalDaftar"`
	NomorAntrian     pgtype.Int2      `json:"nomorAntrian"`
	JadwalTanggal    pgtype.Date      `json:"jadwalTanggal"`
	JadwalJamMulai   pgtype.Time      `json:"jadwalJamMulai"`
	JadwalJamSelesai pgtype.Time      `json:"jadwalJamSelesai"`
	LokasiKelurahan  pgtype.Text      `json:"lokasiKelurahan"`
	NamaLengkap      pgtype.Text      `json:"namaLengkap"`
}

func (q *Queries) GetPermohonanByKodeBooking(ctx context.Context, kodeBooking pgtype.Text) (GetPermohonanByKodeBookingRow, error) {
	row := q.db.QueryRow(ctx, getPermohonanByKodeBooking, kodeBooking)
	var i GetPermohonanByKodeBookingRow
	err := row.Scan(
		&i.ID,
		&i.KodeBooking,
		&i.JenisPermohonan,
		&i.StatusTerkini,
		&i.TanggalDaftar,
		&i.NomorAntrian,
		&i.JadwalTanggal,
		&i.JadwalJamMulai,
		&i.JadwalJamSelesai,
		&i.LokasiKelurahan,
		&i.NamaLengkap,
	)
	return i, err
}

const getPermohonanByNIK = `-- name: GetPermohonanByNIK :many
SELECT 
    p.id,
    p.kode_booking,
    p.jenis_permohonan,
    p.status_terkini,
    p.nomor_antrian_sesi as nomor_antrian,
    p.created_at,
    js.tanggal as jadwal_tanggal,
    js.jam_mulai as jadwal_jam_mulai,
    js.jam_selesai as jadwal_jam_selesai,
    k.nama_kelurahan as lokasi_kelurahan
FROM permohonan p
LEFT JOIN jadwal_sesi js ON p.jadwal_sesi_id = js.id
LEFT JOIN ref_kelurahan k ON js.lokasi_kelurahan_id = k.id
WHERE p.nik = $1
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type GetPermohonanByNIKParams struct {
	Nik    pgtype.Text `json:"nik"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetPermohonanByNIKRow struct {
	ID               uuid.UUID        `json:"id"`
	KodeBooking      pgtype.Text      `json:"kodeBooking"`
	JenisPermohonan  string           `json:"jenisPermohonan"`
	StatusTerkini    pgtype.Text      `json:"statusTerkini"`
	NomorAntrian     pgtype.Int2      `json:"nomorAntrian"`
	CreatedAt        pgtype.Timestamp `json:"createdAt"`
	JadwalTanggal    pgtype.Date      `json:"jadwalTanggal"`
	JadwalJamMulai   pgtype.Time      `json:"jadwalJamMulai"`
	JadwalJamSelesai pgtype.Time      `json:"jadwalJamSelesai"`
	LokasiKelurahan  pgtype.Text      `json:"lokasiKelurahan"`
}

func (q *Queries) GetPermohonanByNIK(ctx context.Context, arg GetPermohonanByNIKParams) ([]GetPermohonanByNIKRow, error) {
	rows, err := q.db.Query(ctx, getPermohonanByNIK, arg.Nik, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPermohonanByNIKRow
	for rows.Next() {
		var i GetPermohonanByNIKRow
		if err := rows.Scan(
			&i.ID,
			&i.KodeBooking,
			&i.JenisPermohonan,
			&i.StatusTerkini,
			&i.NomorAntrian,
			&i.CreatedAt,
			&i.JadwalTanggal,
			&i.JadwalJamMulai,
			&i.JadwalJamSelesai,
			&i.LokasiKelurahan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
